### ISSUE TITLE
Bug on open ai library

### ISSUE THREAD

**Issue by FreitasVarejo** [Intelligent-CAT-Lab/AlphaTrans#12]
Hi!! i keep getting the following error when im trying to use the scripts/translate_fragment.sh. Even though im using the deekseek-coder instead of gpt im getting an error of the open ai library:

> (alphatrans) gabriel.pinheiro@12073640fd7a:/work/gabriel.pinheiro/AlphaTrans$ bash scripts/translate_fragment.sh JavaFastPFOR 0.0 deepseek-coder-33b-instruct
>   0%|                                                                                                                                                                                                                | 0/896 [00:00<?, ?it/s]
> Traceback (most recent call last):
>   File "/work/gabriel.pinheiro/AlphaTrans/src/translation/compositional_translation_validation.py", line 622, in <module>
>     main(args)
>   File "/work/gabriel.pinheiro/AlphaTrans/src/translation/compositional_translation_validation.py", line 603, in main
>     translate(fragment, args, processed_fragments, recursion_depth=args.recursion_depth)
>   File "/work/gabriel.pinheiro/AlphaTrans/src/translation/compositional_translation_validation.py", line 346, in translate
>     client = OpenAI(**{k: v for k, v in model_info[args.model_name].items() if k in ['api_key', 'base_url', 'default_headers']})
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/gabriel.pinheiro/miniconda3/envs/alphatrans/lib/python3.11/site-packages/openai/_client.py", line 123, in __init__
>     super().__init__(
>   File "/home/gabriel.pinheiro/miniconda3/envs/alphatrans/lib/python3.11/site-packages/openai/_base_client.py", line 856, in __init__
>     self._client = http_client or SyncHttpxClientWrapper(
>                                   ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/gabriel.pinheiro/miniconda3/envs/alphatrans/lib/python3.11/site-packages/openai/_base_client.py", line 754, in __init__
>     super().__init__(**kwargs)
> TypeError: Client.__init__() got an unexpected keyword argument 'proxies'
>   0%|                                                                                                                                                                                                               | 0/1191 [00:00<?, ?it/s]
> Traceback (most recent call last):
>   File "/work/gabriel.pinheiro/AlphaTrans/src/translation/compositional_translation_validation.py", line 622, in <module>
>     main(args)
>   File "/work/gabriel.pinheiro/AlphaTrans/src/translation/compositional_translation_validation.py", line 603, in main
>     translate(fragment, args, processed_fragments, recursion_depth=args.recursion_depth)
>   File "/work/gabriel.pinheiro/AlphaTrans/src/translation/compositional_translation_validation.py", line 346, in translate
>     client = OpenAI(**{k: v for k, v in model_info[args.model_name].items() if k in ['api_key', 'base_url', 'default_headers']})
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/gabriel.pinheiro/miniconda3/envs/alphatrans/lib/python3.11/site-packages/openai/_client.py", line 123, in __init__
>     super().__init__(
>   File "/home/gabriel.pinheiro/miniconda3/envs/alphatrans/lib/python3.11/site-packages/openai/_base_client.py", line 856, in __init__
>     self._client = http_client or SyncHttpxClientWrapper(
>                                   ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/gabriel.pinheiro/miniconda3/envs/alphatrans/lib/python3.11/site-packages/openai/_base_client.py", line 754, in __init__
>     super().__init__(**kwargs)
> TypeError: Client.__init__() got an unexpected keyword argument 'proxies'
> 

Ahead is my model_confic.yams, i've checked and the base url is working. Please let me know if i did something wrong:

```
models:
  gpt-4o-2024-11-20:
    model_id: gpt-4o-2024-11-20
    base_url:
    api_key: ""
    default_headers: {}
    total: 128000
    max_new_tokens: 16384
  deepseek-coder-33b-instruct:
    model_id: deepseek-coder:33b-instruct
    base_url: "http://ollama_server:5000"
    api_key: ""
    default_headers: {}
    total: 16384
    max_new_tokens: 4096

```

**Comment by alibrahimzada** [comment]
Please make sure you are using OpenAI version `1.53.0` as mentioned in the `environment.yaml` file. I also believe your `base_url` entry should have `/v1` in the end. See below:

```
models:
  gpt-4o-2024-11-20:
    model_id: gpt-4o-2024-11-20
    base_url:
    api_key: ""
    default_headers: {}
    total: 128000
    max_new_tokens: 16384
  deepseek-coder-33b-instruct:
    model_id: deepseek-coder:33b-instruct
    base_url: "http://ollama_server:5000/v1"
    api_key: ""
    default_headers: {}
    total: 16384
    max_new_tokens: 4096
```
